-- Phone number on daily itineraries + per-day phone audit snapshot.
-- Safe to re-run. Match inventory by last 10 digits (+1908… vs 908-…).

USE fleetdb;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME IN ('DAILY_ITINERARIES', 'daily_itineraries')
     AND COLUMN_NAME IN ('PHONENUMBER', 'phonenumber')) = 0,
  'ALTER TABLE DAILY_ITINERARIES ADD COLUMN PHONENUMBER VARCHAR(20) DEFAULT NULL AFTER TOTAL_BREAKTIME',
  'SELECT ''PHONENUMBER already on DAILY_ITINERARIES'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS phone_audit (
  PHONE_AUDITID INT(11) NOT NULL AUTO_INCREMENT,
  ENTITYID INT(11) NOT NULL DEFAULT 1,
  PHONEID INT(11) DEFAULT NULL,
  PHONENUMBER VARCHAR(20) DEFAULT NULL,
  AUDIT_DATE DATETIME DEFAULT NULL,
  AUDIT_RESULT VARCHAR(20) NOT NULL,
  SOURCE VARCHAR(20) NOT NULL DEFAULT 'itinerary',
  CREATE_USER VARCHAR(100) DEFAULT NULL,
  CREATE_DATE DATETIME DEFAULT NULL,
  UPDATE_USER VARCHAR(100) DEFAULT NULL,
  UPDATE_DATE DATETIME DEFAULT NULL,
  STATUS INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (PHONE_AUDITID),
  KEY IX_PHONE_AUDIT_DAY (ENTITYID, AUDIT_DATE, STATUS),
  KEY IX_PHONE_AUDIT_PHONE (PHONEID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
