-- Expand PHONES for carrier spreadsheet fields.
-- Validity is renamed to CONTRACTENDDATE. Safe to re-run.

USE fleetdb;

-- Rename VALIDITY -> CONTRACTENDDATE
SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'VALIDITY') > 0
  AND (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'CONTRACTENDDATE') = 0,
  'ALTER TABLE phones CHANGE COLUMN VALIDITY CONTRACTENDDATE datetime DEFAULT NULL',
  'SELECT ''CONTRACTENDDATE already in place'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'CURRENTSTATUS') = 0,
  'ALTER TABLE phones ADD COLUMN CURRENTSTATUS int DEFAULT 0 COMMENT ''0 In Use, 1 Not Used, 2 Damaged, 3 Lost'' AFTER PHONESTATUS',
  'SELECT ''CURRENTSTATUS already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'CONTRACTSTARTDATE') = 0,
  'ALTER TABLE phones ADD COLUMN CONTRACTSTARTDATE datetime DEFAULT NULL AFTER CONTRACTENDDATE',
  'SELECT ''CONTRACTSTARTDATE already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'DEVICEMAKE') = 0,
  'ALTER TABLE phones ADD COLUMN DEVICEMAKE varchar(50) DEFAULT NULL AFTER SERIALNUMBER',
  'SELECT ''DEVICEMAKE already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'DEVICEMODEL') = 0,
  'ALTER TABLE phones ADD COLUMN DEVICEMODEL varchar(80) DEFAULT NULL AFTER DEVICEMAKE',
  'SELECT ''DEVICEMODEL already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'IMEI2') = 0,
  'ALTER TABLE phones ADD COLUMN IMEI2 varchar(20) DEFAULT NULL AFTER DEVICEMODEL',
  'SELECT ''IMEI2 already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'IMSI') = 0,
  'ALTER TABLE phones ADD COLUMN IMSI varchar(20) DEFAULT NULL AFTER IMEI2',
  'SELECT ''IMSI already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'ICCID') = 0,
  'ALTER TABLE phones ADD COLUMN ICCID varchar(32) DEFAULT NULL AFTER IMSI',
  'SELECT ''ICCID already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'EID') = 0,
  'ALTER TABLE phones ADD COLUMN EID varchar(40) DEFAULT NULL AFTER ICCID',
  'SELECT ''EID already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'DEVICEORDEREDDATE') = 0,
  'ALTER TABLE phones ADD COLUMN DEVICEORDEREDDATE datetime DEFAULT NULL AFTER CONTRACTSTARTDATE',
  'SELECT ''DEVICEORDEREDDATE already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'DEVICEORDEREDIMEI') = 0,
  'ALTER TABLE phones ADD COLUMN DEVICEORDEREDIMEI varchar(20) DEFAULT NULL AFTER DEVICEORDEREDDATE',
  'SELECT ''DEVICEORDEREDIMEI already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones' AND COLUMN_NAME = 'DEVICEINUSEDATE') = 0,
  'ALTER TABLE phones ADD COLUMN DEVICEINUSEDATE datetime DEFAULT NULL AFTER DEVICEORDEREDIMEI',
  'SELECT ''DEVICEINUSEDATE already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

ALTER TABLE phones MODIFY COLUMN SERIALNUMBER varchar(32) DEFAULT NULL;

UPDATE phones SET CURRENTSTATUS = 0 WHERE CURRENTSTATUS IS NULL;

SELECT COLUMN_NAME, COLUMN_TYPE, COLUMN_DEFAULT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'phones'
ORDER BY ORDINAL_POSITION;
