-- Soft-delete duplicate DAILY_ITINERARIES rows.
-- Keep the newest live row per ENTITYID + TRANSPORTERID + itinerary day.
-- RecordStatus: 0 = ACTIVE, 1 = DELETE. Tagged UPDATE_USER = 'itin-dup-cleanup'.
-- Workbench 1175: updates by primary key IN list only.

USE fleetdb;

-- Preview
SELECT DATE(ITINARARYDATE) AS itinerary_day,
       COUNT(*) AS live_rows,
       COUNT(DISTINCT TRANSPORTERID) AS transporters,
       COUNT(*) - COUNT(DISTINCT TRANSPORTERID) AS extra_rows
FROM DAILY_ITINERARIES
WHERE STATUS = 0
GROUP BY DATE(ITINARARYDATE)
HAVING extra_rows > 0
ORDER BY itinerary_day DESC;

SELECT COUNT(*) AS extra_rows_to_inactivate
FROM DAILY_ITINERARIES d
JOIN (
  SELECT ENTITYID, TRANSPORTERID, DATE(ITINARARYDATE) AS dte,
         MAX(DAILY_ITINERARIESID) AS keep_id
  FROM DAILY_ITINERARIES
  WHERE STATUS = 0
  GROUP BY ENTITYID, TRANSPORTERID, DATE(ITINARARYDATE)
  HAVING COUNT(*) > 1
) k ON d.ENTITYID = k.ENTITYID
   AND d.TRANSPORTERID = k.TRANSPORTERID
   AND DATE(d.ITINARARYDATE) = k.dte
WHERE d.STATUS = 0
  AND d.DAILY_ITINERARIESID <> k.keep_id;

SET SQL_SAFE_UPDATES = 0;

UPDATE DAILY_ITINERARIES
SET STATUS = 1,
    UPDATE_USER = 'itin-dup-cleanup',
    UPDATE_DATE = NOW()
WHERE STATUS = 0
  AND DAILY_ITINERARIESID IN (
    SELECT id FROM (
      SELECT d.DAILY_ITINERARIESID AS id
      FROM DAILY_ITINERARIES d
      JOIN (
        SELECT ENTITYID, TRANSPORTERID, DATE(ITINARARYDATE) AS dte,
               MAX(DAILY_ITINERARIESID) AS keep_id
        FROM DAILY_ITINERARIES
        WHERE STATUS = 0
        GROUP BY ENTITYID, TRANSPORTERID, DATE(ITINARARYDATE)
        HAVING COUNT(*) > 1
      ) k ON d.ENTITYID = k.ENTITYID
         AND d.TRANSPORTERID = k.TRANSPORTERID
         AND DATE(d.ITINARARYDATE) = k.dte
      WHERE d.STATUS = 0
        AND d.DAILY_ITINERARIESID <> k.keep_id
    ) t
  );

SET SQL_SAFE_UPDATES = 1;

-- After: remaining_dup_groups should be 0
SELECT COUNT(*) AS remaining_dup_groups
FROM (
  SELECT ENTITYID, TRANSPORTERID, DATE(ITINARARYDATE)
  FROM DAILY_ITINERARIES
  WHERE STATUS = 0
  GROUP BY ENTITYID, TRANSPORTERID, DATE(ITINARARYDATE)
  HAVING COUNT(*) > 1
) x;

SELECT COUNT(*) AS live_rows
FROM DAILY_ITINERARIES
WHERE STATUS = 0;

SELECT COUNT(*) AS soft_deleted
FROM DAILY_ITINERARIES
WHERE STATUS = 1
  AND UPDATE_USER = 'itin-dup-cleanup';
