-- MVPx vehicle list: odometer + oil change columns
-- Run on UAT and PROD (fleetdb). Safe to re-run (checks information_schema).

USE fleetdb;

-- ODOMETER
SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vehicle' AND COLUMN_NAME = 'ODOMETER') = 0,
  'ALTER TABLE vehicle ADD COLUMN ODOMETER INT NULL COMMENT ''Current odometer reading (miles)'' AFTER VINNUMBER',
  'SELECT ''ODOMETER already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- LAST_ODOMETER_REPORTED_DATE
SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vehicle' AND COLUMN_NAME = 'LAST_ODOMETER_REPORTED_DATE') = 0,
  'ALTER TABLE vehicle ADD COLUMN LAST_ODOMETER_REPORTED_DATE DATE NULL COMMENT ''Date odometer was last reported'' AFTER ODOMETER',
  'SELECT ''LAST_ODOMETER_REPORTED_DATE already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- LAST_OIL_CHANGE_MILEAGE
SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vehicle' AND COLUMN_NAME = 'LAST_OIL_CHANGE_MILEAGE') = 0,
  'ALTER TABLE vehicle ADD COLUMN LAST_OIL_CHANGE_MILEAGE INT NULL COMMENT ''Odometer at last oil change'' AFTER LAST_ODOMETER_REPORTED_DATE',
  'SELECT ''LAST_OIL_CHANGE_MILEAGE already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- LAST_OIL_CHANGE_DATE
SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vehicle' AND COLUMN_NAME = 'LAST_OIL_CHANGE_DATE') = 0,
  'ALTER TABLE vehicle ADD COLUMN LAST_OIL_CHANGE_DATE DATE NULL COMMENT ''Date of last oil change'' AFTER LAST_OIL_CHANGE_MILEAGE',
  'SELECT ''LAST_OIL_CHANGE_DATE already exists'' AS note');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Verify
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'vehicle'
  AND COLUMN_NAME IN (
    'ODOMETER', 'LAST_ODOMETER_REPORTED_DATE',
    'LAST_OIL_CHANGE_MILEAGE', 'LAST_OIL_CHANGE_DATE'
  )
ORDER BY ORDINAL_POSITION;
